version: '3'
services:
  mysql-server:
    image: mysql:latest
    hostname: mysql.challenge.com
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'669440627466909c972d00d5a695c9f4e1e931e1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      MYSQL_ROOT_PASSWORD: 669440627466909c972d00d5a695c9f4e1e931e1
      MYSQL_DATABASE: security
    networks:
      - private_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

networks:
  private_network:
    external: true